name: Continuous Integration

on:
  push:
    branches: ['**']

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Install system requirements'
        run: |
          sudo apt update
          sudo apt install -y libicu-dev
          sudo apt-fast install -y --no-install-recommends \
            php7.4 php7.4-ctype php7.4-intl php7.4-mbstring php7.4-pcov php7.4-sqlite php7.4-xml

      - name: 'Load the keys used to deploy the PHAR archive'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_SIGNING_KEY }}" | gpg --import

      - name: 'Configure the committer identity'
        run: |
          git config --global user.email "info@ajardin.fr"
          git config --global user.name "Alexandre Jardin"
          git config --global commit.gpgsign "true"
          git config --global user.signingkey "405DC05A6F8FFBA9"

      - name: 'Install Composer dependencies'
        run: composer install --optimize-autoloader --classmap-authoritative

      - name: 'Execute PHP-CS-Fixer in dry-run'
        run: make phpcsfixer-audit

      - name: 'Execute a copy/paste analysis'
        run: make phpcpd

      - name: 'Execute PHPStan analysis'
        run: make phpstan

      - name: 'Execute security analysis'
        run: make security

      - name: 'Execute PHPUnit tests and send report to Codecov'
        run: |
          make tests
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
